name       : haskell-regex-tdfa
version    : 1.3.1.0
release    : 7
source     :
    - https://hackage.haskell.org/package/regex-tdfa-1.3.1.0/regex-tdfa-1.3.1.0.tar.gz : 15c376783d397b3b9933cf35980808feddde273bd6f2445babbccb2f76a42ec0
license    : BSD-3-Clause
component  : programming.haskell
summary    : A new all Haskell tagged DFA regex engine, inspired by libtre
description: |
    A new all Haskell tagged DFA regex engine, inspired by libtre
builddeps  :
    - haskell-cabal-install
    - haskell-regex-base-devel
    - haskell-semigroups-devel
rundeps    :
    - devel:
        - haskell-regex-base-devel
        - haskell-semigroups-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
