name       : haskell-regex-tdfa
version    : 1.2.2
release    : 4
source     :
    - https://hackage.haskell.org/package/regex-tdfa-1.2.2/regex-tdfa-1.2.2.tar.gz : cb12d675be7b31ed8086d8d022023d03eb553e55dbee6e1b7a4154933d471d39
license    : BSD-3-Clause
component  : programming.haskell
summary    : A new all Haskell tagged DFA regex engine, inspired by libtre
description: |
    A new all Haskell tagged DFA regex engine, inspired by libtre
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-parsec
    - haskell-regex-base
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
