name       : haskell-regex-tdfa
version    : 1.2.3
release    : 6
source     :
    - https://hackage.haskell.org/package/regex-tdfa-1.2.3/regex-tdfa-1.2.3.tar.gz : 89b17ebb812d4597c0007fbbc21c78dfef70a133aa41b208217a9c99bed600d9
license    : BSD-3-Clause
component  : programming.haskell
summary    : A new all Haskell tagged DFA regex engine, inspired by libtre
description: |
    A new all Haskell tagged DFA regex engine, inspired by libtre
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-parsec
    - haskell-regex-base
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
